export enum DatabasePaths {
  Users = 'users',
  Tournaments = 'tournaments',
  Teams = 'teams',
  Establishments = 'establishments',
  Addresses = 'addresses',
  Tables = 'tables',
  Bookings = 'bookings',
  BalanceHistory = 'balanceHistory',
  Friends = 'friends',
  Categories = 'categories',
  Products = 'products',
  Basket = 'basket',
  OrderConfirmation = 'orderConfirmation',
  Invite = 'invite',
}
